[package]
authors = ["Praveen Perera <praveen@avencera.com>"]
edition = "2018"
name = "rustywind"
version = "0.12.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cli
clap = "2.33"
indoc = "1.0"

# files
ignore = "0.4"

# utils
itertools = "0.10"
lazy_static = "1.4.0"

# string matching
aho-corasick = "0.7"
regex = "1"

# parallel
rayon = "1.5"

[dev-dependencies]
pretty_assertions = "1.0"

[profile.release]
lto = true
